config/routes.rb
Rails.application.routes.draw do

  get '/users/friend_goal',          to: 'users#friend_goal'
  patch 'relationships/accept_friend_request'
  get   'relationships/:id/new',              to:'relationships#new'
  get   'relationships/requests_status',      to:'relationships#requests_status',as: :requests_status
  post  'relationships/:id/create',           to:'relationships#create',as: :create_relationships
  get   'relationships/destroy'

  resources :weekly_goals
  resources :tasks
  resources :monthly_goals do 
    member do 
      get 'my_goal'
    end
  end



  #  deviseが用意しているデフォルトのコントローラーを使わず自分の環境のusersディレクトリは配下のコントローラーを使えというメソッド
  devise_for :users,  controllers: {
    registrations:  'users/registrations',
    confirmations:  'users/confirmations',
    sessions:       'users/sessions',
     }
  
     #↓は↑のusersディレクトリは配下のコントローラーにつなげるようにルーティングを作成するメソッド
     devise_scope :user do
      get '/confirmation_email', to: 'users/confirmations#check_email'
      get '/monthly_goals/new',  to: 'users/monthly_goals#new'
      delete '/logout',          to: 'users/sessions#destroy'
      get '/sign_up',            to: 'users/sessions#new'  
      get '/sign_up_account',    to: 'users/registrations#new'  
      post 'register',           to: 'users/registrations#create'  
  
    end
  
  resources :users do
    collection do
      get 'search' => 'users#search'
    end
  end

   post '/monthly_goals/:id/my_goal', to: 'weekly_goals#create'
   get '/notifications/index',        to: 'notifications#index'


 


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :sender,     class_name: "User", foreign_key: "sender_id"
  belongs_to :reciever,   class_name: "User", foreign_key: "reciever_id"
  validates :sender_id,   presence: true, uniqueness: true
  validates :reciever_id, presence: true, uniqueness: true


  def self.get_sender(friend_request_reciever)
    if !friend_request_reciever.nil?
        friend_request_reciever.sender
    end 
  end 


  

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_q,       only: %i[new create requests_status]
  before_action :friend_user, only: %i[new create ]
  def new
    @user = current_user
    @relationship = Relationship.new
  end

   #can_follow?メソッドの引数の可読性を上げるために@other_usersを作成しました。
  def create
    @other_user =  params[:relationship][:reciever_id]
   if current_user.can_follow?(@other_user,current_user)
    current_user.follow(@other_user,relationship_params,current_user) 
    redirect_to  my_goal_monthly_goal_path(current_user), notice: "友達申請を送信しました"
   else
    redirect_to  my_goal_monthly_goal_path(current_user),flash: { alert: "友達申請送信失敗しました"  }
   end
  end 


  def destroy   
  end

  def requests_status
    @friend_request_reciever = current_user.reciever_relationships
    @friend_request_sender =  Relationship.get_sender(@friend_request_reciever)
  end

  def accept_friend_request

    reciever_user =  current_user.reciever_relationships
    reciever_user.update_column(:checked, "true")
    current_user.create_notification!('accept',current_user,reciever_user.sender_id)

  end


  

  private 

  def set_q
    @q = User.ransack(params[:q])
  end

  def relationship_params
    params.require(:relationship).permit(:sender_id,:reciever_id )
  end 

  def friend_user
    @friend_user = User.find(params[:id])
  end
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/new.html.slim
- if @user.recieved_or_sent_friend_request?(@user)
  h1 目標共有申請依頼
  h2 = "#{@friend_user.name} さんと目標を共有しますか？"

  = button_to "いいえ",  my_goal_monthly_goal_path(@user), method: :get
  = form_with model: @relationship, url:  create_relationships_path do |f|
    = f.hidden_field :sender_id,   value:  current_user.id 
    = f.hidden_field :reciever_id, value:  @friend_user.id 
    = f.submit "はい"
- else 
  h3 目標共有申請を送ることはできません
  p 
    | 下記に該当している可能性があります
  ul
    li 過去に１度目標共有申請依頼を他のユーザーに送っている
    li 他のユーザーから目標共有申請をいただいている

app/views/relationships/requests_status.html.slim
- if @friend_request_reciever.nil?
  h1 なにもありません
  = button_to "戻る",my_goal_monthly_goal_path(current_user),{method: :get}

- else
  h2 #{@friend_request_sender.name}さんから友達申請依頼が届いてます
  = button_to "許可",relationships_accept_friend_request_path,{method: :patch}
  = button_to "拒否",my_goal_monthly_goal_path(current_user),{method: :get}