config/routes.rb
Rails.application.routes.draw do

  get '/users/friend_goal',          to: 'users#friend_goal'
  patch 'relationships/accept_friend_request'
  get   'relationships/:id/new',              to:'relationships#new'
  get   'relationships/requests_status',      to:'relationships#requests_status',as: :requests_status
  post  'relationships/:id/create',           to:'relationships#create',as: :create_relationships
  get   'relationships/destroy'

  resources :weekly_goals
  resources :tasks
  resources :monthly_goals do 
    member do 
      get 'my_goal'
    end
  end



  #  deviseが用意しているデフォルトのコントローラーを使わず自分の環境のusersディレクトリは配下のコントローラーを使えというメソッド
  devise_for :users,  controllers: {
    registrations:  'users/registrations',
    confirmations:  'users/confirmations',
    sessions:       'users/sessions',
     }
  
     #↓は↑のusersディレクトリは配下のコントローラーにつなげるようにルーティングを作成するメソッド
     devise_scope :user do
      get '/confirmation_email', to: 'users/confirmations#check_email'
      get '/monthly_goals/new',  to: 'users/monthly_goals#new'
      delete '/logout',          to: 'users/sessions#destroy'
      get '/sign_up',            to: 'users/sessions#new'  
      get '/sign_up_account',    to: 'users/registrations#new'  
      post 'register',           to: 'users/registrations#create'  
  
    end
  
  resources :users do
    collection do
      get 'search' => 'users#search'
    end
  end

   post '/monthly_goals/:id/my_goal', to: 'weekly_goals#create'
   get '/notifications/index',        to: 'notifications#index'


 


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/views/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation data-turbo-cache=false
    h2
      = I18n.t("errors.messages.not_saved",
               count: resource.errors.count,
               resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li = message

app/views/shared/_flash_message.html.slim
  - flash.each do |message_type, message| 
    .alert class = "alert-#{bootstrap_alert(message_type)}"
      = message

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>


<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/shared/_validation_errors.html.slim
  - if instance.errors.any?
    #error_explanation
      h2 = "#{pluralize(instance.errors.count, "エラー")} "
      ul
        - instance.errors.full_messages.each do |message|
          li = message
  