config/routes.rb
Rails.application.routes.draw do

  get '/users/friend_goal',          to: 'users#friend_goal'
  patch 'relationships/accept_friend_request'
  get   'relationships/:id/new',              to:'relationships#new'
  get   'relationships/requests_status',      to:'relationships#requests_status',as: :requests_status
  post  'relationships/:id/create',           to:'relationships#create',as: :create_relationships
  get   'relationships/destroy'

  resources :weekly_goals
  resources :tasks
  resources :monthly_goals do 
    member do 
      get 'my_goal'
    end
  end



  #  deviseが用意しているデフォルトのコントローラーを使わず自分の環境のusersディレクトリは配下のコントローラーを使えというメソッド
  devise_for :users,  controllers: {
    registrations:  'users/registrations',
    confirmations:  'users/confirmations',
    sessions:       'users/sessions',
     }
  
     #↓は↑のusersディレクトリは配下のコントローラーにつなげるようにルーティングを作成するメソッド
     devise_scope :user do
      get '/confirmation_email', to: 'users/confirmations#check_email'
      get '/monthly_goals/new',  to: 'users/monthly_goals#new'
      delete '/logout',          to: 'users/sessions#destroy'
      get '/sign_up',            to: 'users/sessions#new'  
      get '/sign_up_account',    to: 'users/registrations#new'  
      post 'register',           to: 'users/registrations#create'  
  
    end
  
  resources :users do
    collection do
      get 'search' => 'users#search'
    end
  end

   post '/monthly_goals/:id/my_goal', to: 'weekly_goals#create'
   get '/notifications/index',        to: 'notifications#index'


 


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/monthly_goal.rb
class MonthlyGoal < ApplicationRecord

  belongs_to :user
  has_many :weekly_goals
  mount_uploader :image,ImageUploader

  validates :monthly_goal , presence:true, length: { maximum: 100 }
  validates :penalty_name , presence:true, length: { maximum: 100 }
  



def calc_days(goal_achieved_at)
  today = Date.today 
  @days_until_achievement =  goal_achieved_at - today 

end



end

app/controllers/monthly_goals_controller.rb
class MonthlyGoalsController < ApplicationController
  before_action :set_monthly_goal, only: %i[ show edit update destroy ]
  before_action :set_q,            only: %i[ my_goal new ]
 
 

  def index

  end
  # GET /monthly_goals or /monthly_goals.json
  def my_goal
    @currrent_user = current_user
    @monthly_goal = @current_user.monthly_goal
    @days_until_achievement = @monthly_goal.calc_days(@monthly_goal.goal_achieved_at)
    @weekly_goals = @current_user.weekly_goals
    @events = @current_user.collect_user_events(@weekly_goals)
    @task = Task.new
  end

  # GET /monthly_goals/1 or /monthly_goals/1.json
  def show
  end

  # GET /monthly_goals/new
  def new
    @monthly_goal = MonthlyGoal.new
    @user = current_user
    
  end

  # GET /monthly_goals/1/edit
  def edit
  end

  # POST /monthly_goals or /monthly_goals.json
  def create
    
    @current_user = current_user
    @monthly_goal = @current_user.build_monthly_goal(monthly_goal_params)
    respond_to do |format|
      if @monthly_goal.save
        format.html { redirect_to my_goal_monthly_goal_url(@monthly_goal),flash: { notice: "月間目標が作成されました"} }
        format.json { render :show, status: :created, location: @monthly_goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @monthly_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monthly_goals/1 or /monthly_goals/1.json
  def update
    respond_to do |format|
      if @monthly_goal.update(judge_params)

        format.html { redirect_to  my_goal_monthly_goal_url(@monthly_goal), notice: "Monthly goal was successfully updated." }

        format.json { render :show, status: :ok, location: @monthly_goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @monthly_goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthly_goals/1 or /monthly_goals/1.json
  def destroy
    @monthly_goal.destroy

    respond_to do |format|
      format.html { redirect_to monthly_goals_url, notice: "Monthly goal was successfully destroyed." }
      format.json { head :no_content }
    end
  end




  

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monthly_goal
      @monthly_goal = MonthlyGoal.find(params[:id])
    end

   

    # Only allow a list of trusted parameters through.
    def monthly_goal_params
      params.require(:monthly_goal).permit(:monthly_goal, :goal_achieved_at, :penalty_name, :image)
    end       

      def only_monthly_goal_params
      params.require(:monthly_goal).permit(:monthly_goal)
    end

    def only_penalty_name_params
      params.require(:monthly_goal).permit(:penalty_name)
    end

    def only_penalty_image_params
      params.require(:monthly_goal).permit(:image)
    end

    def params_include_monthly_achieved_at_and_monthly_goal?
      params[:monthly_goal].key?(:goal_achieved_at) && params[:monthly_goal].key?(:monthly_goal)
    end

    def params_include_only_monthly_goal?
      params[:monthly_goal].key?(:monthly_goal) 
    end

    def  params_include_only_penalty_goal?
      params[:monthly_goal].key?(:penalty_name) 
    end

    def params_include_only_image?
      params[:monthly_goal].key?(:image)
    end

    def judge_params
        if params_include_monthly_achieved_at_and_monthly_goal?
           monthly_goal_params  # 存在する場合はmonthly_goal_paramsを返す
        elsif params_include_only_monthly_goal?
           only_monthly_goal_params
        elsif params_include_only_penalty_goal?
           only_penalty_name_params
        elsif params_include_only_image?
           only_penalty_image_params
        end
    end

    def set_q
      @q = User.ransack(params[:q])
      @results = @q.result
    end

end

app/helpers/monthly_goals_helper.rb
module MonthlyGoalsHelper
end

app/views/monthly_goals/_form.html.slim
= form_for @monthly_goal do |f|
  - if @monthly_goal.errors.any?
    #error_explanation
      h2 = "#{pluralize(@monthly_goal.errors.count, "error")} prohibited this monthly_goal from being saved:"
      ul
        - @monthly_goal.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :monthly_goal
    = f.text_field :monthly_goal
  .field
    = f.label :goal_achieved_at
    = f.date_field  :goal_achieved_at
  .field
    = f.label :penalty_name
    = f.text_field :penalty_name
  .field
    = f.label :image
    = f.file_field  :image
  
  .actions = f.submit

app/views/monthly_goals/edit.html.slim
h1 Editing monthly_goal

== render "form"

=> link_to "Show", @monthly_goal
'|
=< link_to "Back", monthly_goals_path

app/views/monthly_goals/index.html.slim
#calendar 

app/views/monthly_goals/my_goal.html.slim
= provide(:title, "マイゴール") 
= render 'layouts/header'
h1 =  "#{@current_user.name}さんの目標"

section.monthly_goal
  h2  = "あなたの#{@monthly_goal.goal_achieved_at.strftime('%Y年%m月%d日')}に達成する目標"
  p.change_goal
    = @monthly_goal.monthly_goal
  p
    = link_to '編集', '#', class: 'edit_button'

section 
  h3 = "目標達成まであと#{@days_until_achievement.to_i}日"
  p 
    = "残#{@days_until_achievement.to_i}日"


section 
  h4 やることカレンダー
 
  
  
  = month_calendar attribute: :start_time, end_attribute: :end_time,events: @events do |date, events|
    = date.day
    .dropdown
       button.btn.btn-default.dropdown-toggle(type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" )
        | +
        span.caret 
       ul.dropdown-menu(aria-labelledby="dropdownMenu1")
         li
           a.weekly_goal[href="#" data-toggle="modal" data-target="#myModal" data-day=date] 週間目標
         - if @weekly_goals.blank?

         - else 
          li
            a.task[href="#" data-toggle="modal" data-target="#add_task" data-day=date] タスク
         

    - events.each do |event|
      - if event.is_a?(WeeklyGoal)
        div.container
          p[class = "weekly_goal_link_#{event.id}"]
            = link_to event.weekly_goal ,  '#',class: "weekly_goal_display_#{event.id}", data: { date: event.start_time.to_s, content: event.weekly_goal }
          p 
            = link_to "編集",    '#'  ,        class: "weekly_goal_edit_#{event.id}",data: { id: event.id }
          p 
            = link_to "削除",    '#'  ,        class: "weekly_goal_destroy_#{event.id}"
      - else 
        div
          = link_to event.task,event
        
              
section.penalty
  h5 バディに差出すもの
  p.change_penalty_name = @monthly_goal.penalty_name
  p
    = link_to '編集', '#', class: 'penalty_edit_button'
    
  = image_tag @monthly_goal.image.to_s
  p
    = link_to '編集', '#', class: 'penalty_image_edit'
    
#file-upload-form style="display: none;"
  = form_with model: @monthly_goal , local: true, id: 'image_update' do |f|
    = f.file_field :image
    = f.submit '更新'
= render partial: 'weekly_goals/add_weekly_goal', locals:  {monthly_goal: @monthly_goal}

= render partial: 'tasks/task_modal'



  

= link_to "New Monthly goal", new_monthly_goal_path
= link_to "ログアウト",  logout_path, method: :delete

app/views/monthly_goals/new.html.slim
h1 New monthly_goal

== render "form"

= link_to "Back", monthly_goals_path

app/views/monthly_goals/show.html.slim
p#notice = notice

p
  strong Monthly goal:
  = @monthly_goal.monthly_goal

p
  strong Goal achieved at:
  = @monthly_goal.goal_achieved_at

p
  strong Penalty name:
  = @monthly_goal.penalty_name

p
  strong Image:
  = @monthly_goal.image

p
  strong User:
  = @monthly_goal.user

=> link_to "Edit", edit_monthly_goal_path(@monthly_goal)
'|
=< link_to "Back", monthly_goals_path